import { CHAIN_NAMESPACES } from "@web3auth/modal";

export const chains = {
  ethereum: {
    chainNamespace: CHAIN_NAMESPACES.EIP155,
    chainId: "0x1",
    displayName: "Ethereum Mainnet",
    rpcTarget: "https://1rpc.io/eth",
    blockExplorerUrl: "https://etherscan.io",
    ticker: "ETH",
    tickerName: "Ethereum",
    logo: "https://web3auth.io/images/web3authlog.png",
  },
  sepolia: {
    chainNamespace: CHAIN_NAMESPACES.EIP155,
    chainId: "0xaa36a7",
    displayName: "Ethereum Sepolia",
    tickerName: "Ethereum",
    ticker: "ETH",
    rpcTarget: "https://1rpc.io/sepolia",
    blockExplorerUrl: "https://sepolia.etherscan.io",
    logo: "https://web3auth.io/images/web3authlog.png",
  },
  polygon: {
    chainNamespace: CHAIN_NAMESPACES.EIP155,
    chainId: "0x89",
    rpcTarget: "https://rpc.ankr.com/polygon",
    displayName: "Polygon Mainnet",
    blockExplorerUrl: "https://polygonscan.com",
    ticker: "POL",
    tickerName: "Polygon Ecosystem token",
    logo: "https://web3auth.io/images/web3authlog.png",
  },
  polygonTest: {
    chainNamespace: CHAIN_NAMESPACES.EIP155,
    chainId: "0x13882",
    rpcTarget: "https://rpc.ankr.com/polygon_amoy",
    displayName: "Polygon Amoy Testnet",
    blockExplorerUrl: "https://amoy.polygonscan.com",
    ticker: "POL",
    tickerName: "Polygon Ecosystem token",
    logo: "https://web3auth.io/images/web3authlog.png",
  },
  base: {
    chainNamespace: CHAIN_NAMESPACES.EIP155,
    chainId: "0x14A34",
    rpcTarget: "https://sepolia.base.org",
    displayName: "Base Sepolia",
    blockExplorerUrl: "https://sepolia-explorer.base.org/",
    ticker: "ETH",
    tickerName: "ETH",
    logo: "https://web3auth.io/images/web3authlog.png",
  },
  bnb: {
    chainNamespace: CHAIN_NAMESPACES.EIP155,
    chainId: "0x38",
    rpcTarget: "https://rpc.ankr.com/bsc",
    displayName: "Binance SmartChain Mainnet",
    blockExplorerUrl: "https://bscscan.com/",
    ticker: "BNB",
    tickerName: "BNB",
    logo: "https://web3auth.io/images/web3authlog.png",
  },
  avalanche: {
    chainNamespace: CHAIN_NAMESPACES.EIP155,
    chainId: "0xA86A",
    rpcTarget: "https://rpc.ankr.com/avalanche-c",
    displayName: "Avalanche C-Chain Mainnet",
    blockExplorerUrl: "https://subnets.avax.network/c-chain",
    ticker: "AVAX",
    tickerName: "AVAX",
    logo: "https://web3auth.io/images/web3authlog.png",
  },
  arbitrum: {
    chainNamespace: CHAIN_NAMESPACES.EIP155,
    chainId: "0xA4B1",
    rpcTarget: "https://rpc.ankr.com/arbitrum",
    displayName: "Arbitrum Mainnet",
    blockExplorerUrl: "https://arbiscan.io",
    ticker: "AETH",
    tickerName: "AETH",
    logo: "https://web3auth.io/images/web3authlog.png",
  },
  optimism: {
    chainNamespace: CHAIN_NAMESPACES.EIP155,
    chainId: "0xA",
    rpcTarget: "https://rpc.ankr.com/optimism",
    displayName: "Optimism Mainnet",
    blockExplorerUrl: "https://optimistic.etherscan.io",
    ticker: "OP",
    tickerName: "OP",
    logo: "https://web3auth.io/images/web3authlog.png",
  },
  // ...rest of chains remain the same
};

export const web3AuthChains = Object.values(chains);
